import Link from 'next/link';
import { ArrowUpRight, Mail, MapPin, Phone } from 'lucide-react';
import { tours } from '@/data/tours';
import { destinations } from '@/data/destinations';
import { site } from '@/data/site';
export function Footer() {
  return <footer className="bg-navy text-white"><div className="mx-auto max-w-content px-5 pb-8 pt-16 sm:px-8 lg:pt-20">
    <div className="grid gap-12 border-b border-white/15 pb-16 md:grid-cols-2 lg:grid-cols-4">
      <div><Link href="/" className="font-display text-3xl">Pamir Ecotourism</Link><p className="mt-5 max-w-xs text-sm leading-7 text-white/70">Locally owned journeys through the Pamirs and beyond.</p></div>
      <div><h2 className="mb-5 text-xs font-semibold uppercase tracking-[.2em] text-turquoise">Explore</h2><div className="flex flex-col gap-3 text-sm text-white/75"><Link href="/tours" className="hover:text-white">Tours</Link><Link href="/destinations" className="hover:text-white">Destinations</Link><Link href={`/tours/${tours[0].slug}`} className="hover:text-white">{tours[0].title}</Link><Link href={`/destinations/${destinations[0].slug}`} className="hover:text-white">{destinations[0].name}</Link><Link href="/gallery" className="hover:text-white">Gallery</Link><Link href="/about" className="hover:text-white">About us</Link></div></div>
      <div><h2 className="mb-5 text-xs font-semibold uppercase tracking-[.2em] text-turquoise">Contact</h2><address className="flex flex-col gap-4 text-sm not-italic leading-6 text-white/75"><span className="flex gap-3"><MapPin size={18} className="mt-1 shrink-0 text-gold" aria-hidden="true" />{site.address}</span><a className="flex gap-3 hover:text-white" href={`tel:${site.phoneHref}`}><Phone size={18} className="shrink-0 text-gold" aria-hidden="true" />{site.phone}</a><a className="flex gap-3 break-all hover:text-white" href={`mailto:${site.email}`}><Mail size={18} className="shrink-0 text-gold" aria-hidden="true" />{site.email}</a></address></div>
      <div><h2 className="mb-5 text-xs font-semibold uppercase tracking-[.2em] text-turquoise">Stay in touch</h2><p className="mb-4 text-sm leading-6 text-white/70">Newsletter sign-up is coming soon.</p><label htmlFor="newsletter-email" className="sr-only">Email address for newsletter</label><input id="newsletter-email" type="email" placeholder="Your email address" disabled aria-describedby="newsletter-status" className="w-full rounded-brand border border-white/20 bg-white/10 px-4 py-3 text-white placeholder:text-white/50 disabled:cursor-not-allowed" /><p id="newsletter-status" className="mt-2 text-xs text-white/60">Sign-up will open when the newsletter launches.</p><div className="mt-6 flex gap-5 text-sm"><a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" aria-label="Instagram (platform homepage)" className="inline-flex items-center gap-1 hover:text-gold">Instagram <ArrowUpRight size={14} /></a><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook (platform homepage)" className="inline-flex items-center gap-1 hover:text-gold">Facebook <ArrowUpRight size={14} /></a></div><p className="mt-2 text-xs text-white/50">Official social profile links pending confirmation.</p></div>
    </div><div className="flex flex-col gap-3 pt-7 text-xs text-white/50 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} Pamir Ecotourism</span><span>Based in Rushan, Tajikistan</span></div>
  </div></footer>;
}
